# mappings "current_name": "common_name"

name_mappings = {
    "SandeepSharma": "Sandeep Sharma",
    "Rinku Singh": "Rinku Singh",
    "Abhishek": "Abhishek Sharma",
    "Prithvi Shaw": "Prithvi Shaw",
    "gautamgambhir": "Gautam Gambhir",
    "Sai Sudharsan": "Sai Sudharsan",
    "shashanksingh": "Shashank Singh",
    "Wadhera": "Nehal Wadhera",
    "ShreyasIyer": "Shreyas Iyer",
    "Nabi": "Mohammad Nabi",
    "Mohsin Khan": "Mohsin Khan",
    "MumbaiIndians": "Mumbai Indians",
    "Rishabh Pant": "Rishabh Pant",
    "Axar Patel": "Axar Patel",
    "Natarajan": "T Natarajan",
    "Devon Conway": "Devon Conway",
    "Deepak Hooda": "Deepak Hooda",
    "klassen": "Heinrich Klaasen",
    "QDK": "Quinton de Kock",
    "Patidar": "Rajat Patidar",
    "Mitchelstrac": "Mitchell Starc",
    "Ruturaj": "Ruturaj Gaikwad",
    "Mumbai Indians": "Mumbai Indians",
    "Shahrukh Khan": "Shahrukh Khan",
    "@23_rahulr": "Lokesh Rahul",
    "Yashshavi Jaiswal": "Yashasvi Jaiswal",
    "virat kohali": "Virat Kohli",
    "Cameron Green": "Cameron Green",
    "Sai Kishore": "R Sai Kishore",
    "ATHIest47": "Atharva Taide",
    "Kaviya Maran": "Kaviya Maran",
    "Anmol": "Anmolpreet Singh",
    "DelhiCapitals": "Delhi Capitals",
    "Ritu": "Ritu Kumari",
    "PBKS": "Punjab Kings",
    "DK": "Dinesh Karthik",
    "Ashutosh Sharma": "Ashutosh Aman",
    "Shah Rukh Khan": "Shah Rukh Khan",
    "JakeFraser-McGurk": "Jake Fraser-McGurk",
    "DONI": "MS Dhoni",
    "Mcgurk": "Jake Fraser-McGurk",
    "Ranbir Kapoor": "Ranbir Kapoor",
    "Starc": "Mitchell Starc",
    "Royal Challengers Bengaluru": "Royal Challengers Bangalore",
    "YuzvendraChahal": "Yuzvendra Chahal",
    "PhilSalt": "Philip Salt",
    "Dale Steyn": "Dale Steyn",
    "Markram": "Aiden Markram",
    "Karn": "Karn Sharma",
    "bhogleharsha": "Harsha Bhogle",
    "Preity Zinta": "Preity Zinta",
    "Jansen": "Marco Jansen",
    "Purple Patel": "Axar Patel",
    "MS": "MS Dhoni",
    "kuldeep yaadav": "Kuldeep Yadav",
    "mahi": "MS Dhoni",
    "K L Rahul": "KL Rahul",
    "David Warner": "David Warner",
    "Shreyash": "Shreyas Iyer",
    "Gautham Gambhir": "Gautam Gambhir",
    "Royal Challengers Banglore": "Royal Challengers Bangalore",
    "Srh bowlers": "Sunrisers Hyderabad (SRH)",
    "Venkatesh Iyer": "Venkatesh Iyer",
    "RCB fans": "Royal Challengers Bangalore",
    "davidwarner31": "David Warner",
    "Daniel Vettori": "Daniel Vettori",
    "Cameron White": "Cameron White",
    "Aiden Markram": "Aiden Markram",
    "KKR": "Kolkata Knight Riders",
    "MS Dhoni": "MS Dhoni",
    "#DC": "Delhi Capitals",
    "CSK": "Chennai Super Kings",
    "Sanju": "Sanju Samson",
    "Sanjay Manjrekar": "Sanjay Manjrekar",
    "Mohammad Siraj": "Mohammed Siraj",
    "Karthik": "Dinesh Karthik",
    "Rajinikanth": "Rajinikanth",
    "Yashaswi Jaiswal": "Yashasvi Jaiswal",
    "ryanparag": "Riyan Parag",
    "TilakVarma": "Tilak Varma",
    "Chepauk crowd": "Chennai Super Kings",
    "#AbhishekSharma": "Abhishek Sharma",
    "umpire": "Umpire",
    "ImRaina": "Suresh Raina",
    "MayankAggarwal": "Mayank Agarwal",
    "Bhuvneshwar Kumar": "Bhuvneshwar Kumar",
    "Nortje": "Anrich Nortje",
    "Chennai Super Kings": "Chennai Super Kings",
    "Jacks": "Jofra Archer",
    "Bairstow": "Jonny Bairstow",
    "Sundar": "Washington Sundar",
    "Abdul Samad": "Abdul Samad",
    "rohitsharma": "Rohit Sharma",
    "Pandya": "Hardik Pandya",
    "FafduPlessis": "Faf du Plessis",
    "OrangeArmy": "Sunrisers Hyderabad (SRH)",
    "YashasviJaiswal": "Yashasvi Jaiswal",
    "Travis Head": "Travis Head",
    "Ravi Ashwin": "Ravichandran Ashwin",
    "klrahul": "KL Rahul",
    "NehalWadhera": "Nehal Wadhera",
    "दुबे": "Shivam Dube",
    "Mitchell Marsh": "Mitchell Marsh",
    "अभिषेक शर्मा": "Abhishek Sharma",
    "Suresh Raina": "Suresh Raina",
    "Jonny Jonny": "Jonny Bairstow",
    "Rutu": "Ruturaj Gaikwad",
    "David Miller": "David Miller",
    "King Khan": "Shah Rukh Khan",
    "Tristan Stubbs": "Tristan Stubbs",
    "Yogi Babu": "Yogi Babu",
    "NitishRana": "Nitish Rana",
    "Delhi": "Delhi Capitals",
    "mahipal lomror": "Mahipal Lomror",
    "Russell": "Andre Russell",
    "GT": "Gujarat Titans",
    "Virat kohli": "Virat Kohli",
    "Mohammad Nabi": "Mohammad Nabi",
    "Arshdeep Singh": "Arshdeep Singh",
    "Vijaykumar Vyshak": "Vyshak Vijay Kumar",
    "Mahesh Babu": "Mahesh Babu",
    "Ajithkumar": "Ajith Kumar",
    "Warrier": "Sandeep Warrier",
    "Mustafizur Rahman": "Mustafizur Rahman",
    "King": "Kolkata Knight Riders",
    "csk": "Chennai Super Kings",
    "Saha": "Wriddhiman Saha",
    "JUSTIN": "Justin Langer",
    "Glenn Phillips": "Glenn Phillips",
    "Virat Kohli": "Virat Kohli",
    "Munawar Faruqui": "Munawar Faruqui",
    "RohitSharma": "Rohit Sharma",
    "Murali Karthik": "Murali Karthik",
    "Chris Gayle": "Chris Gayle",
    "#SRH": "Sunrisers Hyderabad (SRH)",
    "AidenMarkram": "Aiden Markram",
    "AB De Villiers": "AB de Villiers",
    "Joy Bhattacharj": "Joy Bhattacharj",
    "stoinis": "Marcus Stoinis",
    "ishankishan": "Ishan Kishan",
    "yashasvijaiswal": "Yashasvi Jaiswal",
    "sky": "Suryakumar Yadav",
    "Rilee Rossouw": "Rilee Rossouw",
    "farooqi": "Arshdeep Singh",
    "Kohali": "Virat Kohli",
    "DHONI": "MS Dhoni",
    "RavindraJadeja": "Ravindra Jadeja",
    "JonnyBairstow": "Jonny Bairstow",
    "Arustham": "Arshdeep Singh",
    "faf1307": "Faf du Plessis",
    "ViratKohli": "Virat Kohli",
    "starc": "Mitchell Starc",
    "DJ Bravo": "Dwayne Bravo",
    "lucknowsupergiants": "Lucknow Super Giants",
    "ADIEN MARKRAM": "Aiden Markram",
    "Kumar Sangakkara": "Kumar Sangakkara",
    "RCB": "Royal Challengers Bangalore",
    "SRH players": "Sunrisers Hyderabad (SRH)",
    "Rizvi": "Azim Rizvi",
    "Sharma": "Rohit Sharma",
    "Nitish Reddy": "Nithish Reddy",
    "Jaydev Unadkat": "Jaydev Unadkat",
    "Marco Jansen": "Marco Jansen",
    "Dushmantha Chameera": "Dushmantha Chameera",
    "Rasikh": "Rasikh Salam",
    "kaviyamaran": "Kaviya Maran",
    "Nicky P": "Nicholas Pooran",
    "PRABHSIMRAN SINGH": "Prabhsimran Singh",
    "STARC": "Mitchell Starc",
    "ShahRukh Khan": "Shah Rukh Khan",
    "Tilak Verma": "Tilak Varma",
    "Khaleel Ahmed": "Khaleel Ahmed",
    "Yash Dayal": "Yash Dayal",
    "KKRiders": "Kolkata Knight Riders",
    "manish Batavia": "Manish Pandey",
    "#MSDhoni": "MS Dhoni",
    "Karan Sharma": "Karn Sharma",
    "#Head": "Travis Head",
    "rcb": "Royal Challengers Bangalore",
    "Gill": "Shubman Gill",
    "Mike Hesson": "Mike Hesson",
    "@MStoinis": "Marcus Stoinis",
    "Rahul Tewatia": "Rahul Tewatia",
    "SunilNarine": "Sunil Narine",
    "srk": "Shah Rukh Khan",
    "Venky Varun": "Varun Chakravarthy",
    "Velu": "Murali Vijay",
    "rioworst": "Riyan Parag",
    "Elvish": "Elvis Gomes",
    "Srh": "Sunrisers Hyderabad (SRH)",
    "Faf": "Faf du Plessis",
    "rahul": "Lokesh Rahul",
    "gautam gambhir": "Gautam Gambhir",
    "Dinesh Karthik": "Dinesh Karthik",
    "rajatpatidar": "Rajat Patidar",
    "Manish Batavia": "Manish Pandey",
    "Pawan Kalyan": "Pawan Negi",
    "shabaz": "Shahbaz Ahmed",
    "DS Raj Purohit": "Rajat Patidar",
    "Delhi Capitals": "Delhi Capitals",
    "Dhoni": "MS Dhoni",
    "Delhi Capitals (DC)": "Delhi Capitals",
    "msdhoni": "MS Dhoni",
    "COTTENrana": "Shreyas Iyer",
    "AbRam": "AbRam Khan",
    "Dinesh Kartik": "Dinesh Karthik",
    "Lalit Yadav": "Lalit Yadav",
    "yuzichahal": "Yuzvendra Chahal",
    "gilly381": "Adam Gilchrist",
    "Mitchel Starc": "Mitchell Starc",
    "Ayush Badoni": "Ayush Badoni",
    "SRK": "Shah Rukh Khan",
    "shahrukhkhan": "Shah Rukh Khan",
    "abhisheksharma": "Abhishek Sharma",
    "Virat": "Virat Kohli",
    "KL Rahul": "KL Rahul",
    "NZ": "New Zealand",
    "Sammu baby": "Sanju Samson",
    "RCB players": "Royal Challengers Bangalore",
    "PatCummins": "Pat Cummins",
    "chakaravarthy29": "Varun Chakravarthy",
    "Sara Gill": "Shubman Gill",
    "Pat Cummins": "Pat Cummins",
    "undefined": "Undefined",
    "Royal Challengers of Bangalore": "Royal Challengers Bangalore",
    "Bhuvi": "Bhuvneshwar Kumar",
    "Ishant Sharma": "Ishant Sharma",
    "DC": "Delhi Capitals",
    "Sandeep Warrier": "Sandeep Warrier",
    "Boult": "Trent Boult",
    "Shardul Thakur": "Shardul Thakur",
    "Nithish Reddy": "Nithish Reddy",
    "pathirana": "Jeffrey Vandersay",
    "Head": "Travis Head",
    "Chetan Sakariya": "Chetan Sakariya",
    "Abhi": "Abhishek Sharma",
    "SRH": "Sunrisers Hyderabad (SRH)",
    "RinkuSingh": "Rinku Singh",
    "Suhana Khan": "Suhana Khan",
    "Tufan": "Tufan Ghosh",
    "Ravi Bishnoi": "Ravi Bishnoi",
    "padikkal": "Devdutt Padikkal",
    "Dhruv Jurel": "Dhruv Jurel",
    "Rinku": "Rinku Singh",
    "Chokli": "Deepak Chahar",
    "Ravi vishnoi": "Ravi Bishnoi",
    "Deepak Chahar": "Deepak Chahar",
    "Venky Mysore": "Venky Mysore",
    "Brendon McCullum": "Brendon McCullum",
    "Rachin Ravindra": "Rachin Ravindra",
    "Shivam Dube": "Shivam Dube",
    "Iyer": "Shreyas Iyer",
    "ChennaiIPL": "Chennai Super Kings",
    "MARCUS STOINIS": "Marcus Stoinis",
    "Rohit": "Rohit Sharma",
    "Green": "Cameron Green",
    "Yuvraj singh": "Yuvraj Singh",
    "Jaiswal": "Yashasvi Jaiswal",
    "Jos Butler": "Jos Buttler",
    "Green Jersey": "Cameron Green",
    "DBoss": "Darshan Jariwala",
    "HarshitRana": "Harshit Rana",
    "Jake Fraser McGurk": "Jake Fraser-McGurk",
    "RISABH PANT": "Rishabh Pant",
    "Rushell": "Riyan Parag",
    "#ChennaiSuperKings": "Chennai Super Kings",
    "Akash Chopra": "Akash Chopra",
    "Venky Iyer": "Venkatesh Iyer",
    "Conway": "Devon Conway",
    "Arshaddeep Singh": "Arshdeep Singh",
    "Faf du Plessis": "Faf du Plessis",
    "sanjusamson": "Sanju Samson",
    "Kaptaan": "Virat Kohli",
    "Harbhajan Singh": "Harbhajan Singh",
    "Unadkat": "Jaydev Unadkat",
    "VirenderSehwag": "Virender Sehwag",
    "Narayan Jagadeesan": "Narayan Jagadeesan",
    "Prabhsimran": "Prabhsimran Singh",
    "patcummins30": "Pat Cummins",
    "Sunrisers Hyderabad (SRH)": "Sunrisers Hyderabad (SRH)",
    "HARDIK PANDYA": "Hardik Pandya",
    "Harshit Rana": "Harshit Rana",
    "ShashankSingh": "Shashank Singh",
    "Yuvraj Singh": "Yuvraj Singh",
    "Darren Sammy": "Darren Sammy",
    "chennaisuperkings": "Chennai Super Kings",
    "Vijay Mallya": "Vijay Mallya",
    "Jitesh Sharma": "Jitesh Sharma",
    "Anuj Rawat": "Anuj Rawat",
    "NITISH KUMAR REDDY": "Nithish Reddy",
    "विराट कोहली": "Virat Kohli",
    "Ravindra Jadeja": "Ravindra Jadeja",
    "ROHIT": "Rohit Sharma",
    "#RishabhPant": "Rishabh Pant",
    "Karn Sharma": "Karn Sharma",
    "Gambhir": "Gautam Gambhir",
    "SunRisers": "Sunrisers Hyderabad (SRH)",
    "Naren": "Natarajan",
    "Tarnaka Head": "Travis Head",
    "Siddharth Anand": "Siddharth Anand",
    "Sanju Samson": "Sanju Samson",
    "Mahesh": "Mahesh Babu",
    "manish batavia": "Manish Pandey",
    "mohitsharma": "Mohit Sharma",
    "Sameer": "Sameer",
    "sachin": "Sachin Tendulkar",
    "jaiswal": "Yashasvi Jaiswal",
    "Narine": "Sunil Narine",
    "ABHISHEK SHARMA": "Abhishek Sharma",
    "ChrisGayle": "Chris Gayle",
    "Glen Phillips": "Glenn Phillips",
    "Shahbaz Ahmed": "Shahbaz Ahmed",
    "Oscar Piastri": "Oscar Piastri",
    "None": "Undefined",
    "Mitchell Starc": "Mitchell Starc",
    "MitchellStarc": "Mitchell Starc",
    "Axar": "Axar Patel",
    "virender sehwag": "Virender Sehwag",
    "Chameera": "Dushmantha Chameera",
    "Ramandeep": "Ramandeep",
    "KL": "KL Rahul",
    "Rashid": "Rashid Khan",
    "Rohit Sharma": "Rohit Sharma",
    "MSDhoni": "MS Dhoni",
    "Suryakumar Yadav": "Suryakumar Yadav",
    "Nattu": "Natarajan",
    "Jonty Rhodes": "Jonty Rhodes",
    "@KKRiders": "Kolkata Knight Riders",
    "MaheshBabu": "Mahesh Babu",
    "Mitchell": "Mitchell",
    "Thalaivan": "MS Dhoni",
    "Tushar Deshpande": "Tushar Deshpande",
    "DC skipper": "Rishabh Pant",
    "AB de Villiers": "AB de Villiers",
    "Fraser-McGurk": "Jake Fraser-McGurk",
    "Suyash Prabhudessai": "Suyash Prabhudessai",
    "Samson": "Sanju Samson",
    "Shashank Singh": "Shashank Singh",
    "KKR Team": "Kolkata Knight Riders",
    "kkr bowlers": "Kolkata Knight Riders",
    "Suyash Chameera": "Dushmantha Chameera",
    "Shreyash Iyer": "Shreyas Iyer",
    "dineshkarthik": "Dinesh Karthik",
    "Quinton De Kock": "Quinton de Kock",
    "Steph_I_Will": "Steph_I_Will",
    "Joss Butler": "Jos Buttler",
    "Stubbs": "Tristan Stubbs",
    "KKR batters": "Kolkata Knight Riders",
    "malinga": "Lasith Malinga",
    "Madhapur Markram": "Aiden Markram",
    "thala": "MS Dhoni",
    "Kohli": "Virat Kohli",
    "Tlayanl2": "Undefined",
    "GautamGambhir": "Gautam Gambhir",
    "Moeen Ali": "Moeen Ali",
    "ருத்துராஜ் கெய்க்வாட்": "Ruturaj Gaikwad",
    "BAZ": "Brendon McCullum",
    "Raxnak": "Raxnak",
    "Sakib": "Sakib",
    "srh": "Sunrisers Hyderabad (SRH)",
    "Yuzvendra Chahal": "Yuzvendra Chahal",
    "RR star": "Rajasthan Royals",
    "Du Plessis": "Faf du Plessis",
    "KuldeepYadav": "Kuldeep Yadav",
    "Kuldeep": "Kuldeep Yadav",
    "Kuldeep Yadav": "Kuldeep Yadav",
    "Yashasvi Jaiswal": "Yashasvi Jaiswal",
    "Shubman Gill": "Shubman Gill",
    "Wasim Ibrahim": "Wasim Ibrahim",
    "RR": "Rajasthan Royals",
    "shahbaz ahmad": "Shahbaz Ahmed",
    "Faf Du Plessis": "Faf du Plessis",
    "natarajan": "Natarajan",
    "RCBvKKR": "Royal Challengers Bangalore vs Kolkata Knight Riders",
    "jos buttler": "Jos Buttler",
    "Shivam dube": "Shivam Dube",
    "Suryakumar": "Suryakumar Yadav",
    "Manoj tiwary": "Manoj Tiwary",
    "Varun Chakravarthy": "Varun Chakravarthy",
    "Klassen": "Heinrich Klaasen",
    "Miller": "David Miller",
    "rishabhpant": "Rishabh Pant",
    "ravindrajadeja": "Ravindra Jadeja",
    "Mayank Agarwal": "Mayank Agarwal",
    "Matt Henry": "Matt Henry",
    "Thala": "MS Dhoni",
    "IPL2024": "IPL 2024",
    "Lockie Ferguson": "Lockie Ferguson",
    "shashank": "Shashank",
    "#CSK": "Chennai Super Kings",
    "JaspritBumrah": "Jasprit Bumrah",
    "KHALEEL AHMED": "Khaleel Ahmed",
    "abhi": "Abhishek Sharma",
    "#Thalaivar": "MS Dhoni",
    "Noor": "Noor",
    "SanjuSamson": "Sanju Samson",
    "Skipper": "Captain",
    "Noor Ahmad": "Noor Ahmad",
    "travis head": "Travis Head",
    "Anjellia": "Anjellia",
    "Markande": "Mayank Markande",
    "Mimmalni": "Mimmalni",
    "Phil Salt": "Phil Salt",
    "Swapnil Singh": "Swapnil Singh",
    "Nitish Kumar Reddy": "Nithish Reddy",
    "KarnSharma": "Karn Sharma",
    "Siraj": "Mohammed Siraj",
    "Kedar Jadhav": "Kedar Jadhav",
    "Jayden": "Jayden",
    "Virender Sehwag": "Virender Sehwag",
    "Krunal Pandya": "Krunal Pandya",
    "SandeepWarrier": "Sandeep Warrier",
    "iamsrk": "Shah Rukh Khan",
    "Sunrisers Hyderabad": "Sunrisers Hyderabad (SRH)",
    "Gujrat Titans (GT)": "Gujarat Titans (GT)",
    "TravisHead": "Travis Head",
    "Nitish Rana": "Nitish Rana",
    "Chawla": "Piyush Chawla",
    "Shane Watson": "Shane Watson",
    "HeinrichKlaasen": "Heinrich Klaasen",
    "RCBTweets": "Royal Challengers Bangalore",
    "Hardik": "Hardik Pandya",
    "Matthew Hayden": "Matthew Hayden",
    "Rajath": "Rajath",
    "Ajinkya Rahane": "Ajinkya Rahane",
    "bairstow": "Jonny Bairstow",
    "Vijay Shankar": "Vijay Shankar",
    "Chawla": "Piyush Chawla",
    "Shane Watson": "Shane Watson",
    "HeinrichKlaasen": "Heinrich Klaasen",
    "RCBTweets": "Royal Challengers Bangalore",
    "Hardik": "Hardik Pandya",
    "Matthew Hayden": "Matthew Hayden",
    "Rajath": "Rajat Patidar",
    "Ajinkya Rahane": "Ajinkya Rahane",
    "bairstow": "Jonny Bairstow",
    "Vijay Shankar": "Vijay Shankar",
    "Ashwin": "Ravichandran Ashwin",
    "travishead34": "Travis Head",
    "BochalyaM01": "Undefined",
    "Vennela Kishore": "Vennela Kishore",
    "Will Jacks": "Will Jacks",
    "Jake": "Undefined",
    "Thala Ajith": "Ajith Kumar",
    "GbNaib": "Gulbadin Naib",
    "Sudharsan": "Sai Sudharsan",
    "JONNY BAIRSTOW": "Jonny Bairstow",
    "sunil narine": "Sunil Narine",
    "Sandeepsharma": "Sandeep Sharma",
    "sais_1509": "Undefined",
    "hardikpandya7": "Hardik Pandya",
    "Sachin Tendulkar": "Sachin Tendulkar",
    "abhishek sharma": "Abhishek Sharma",
    "Rovman Powell": "Rovman Powell",
    "MsDhoni": "MS Dhoni",
    "Michael Hussey": "Michael Hussey",
    "Ananya": "Ananya Panday",
    "travishead": "Travis Head",
    "MS dhoni": "MS Dhoni",
    "ashutoshsharma": "Ashutosh Sharma",
    "Moeen": "Moeen Ali",
    "Marcus Stoinus": "Marcus Stoinis",
    "#Thalaiva": "MS Dhoni",
    "kl rahul": "KL Rahul",
    "Shahrukh": "Shahrukh Khan",
    "Thala Dharisanam": "MS Dhoni",
    "dhoni": "MS Dhoni",
    "Royal Rajwade": "Undefined",
    "KraghMarius": "Marius Krag",
    "Ramana": "Undefined",
    "Fizz": "Fizz",
    "ChennaiIPL skipper": "MS Dhoni",
    "Rajasthan Royals": "Rajasthan Royals",
    "Phill Salt": "Phil Salt",
    "Narin": "Undefined",
    "Shikhar Dhawan": "Shikhar Dhawan",
    "TRAVIS HEAD": "Travis Head",
    "Qais Omarzai": "Qais Ahmad",
    "Arshadeep": "Undefined",
    "Priyam Garg": "Priyam Garg",
    "Salt": "Phil Salt",
    "Jurel": "Dhruv Jurel",
    "ImRo45": "Rohit Sharma",
    "Rahane": "Ajinkya Rahane",
    "ShahRukhKhan": "Shahrukh Khan",
    "Quinton": "Quinton de Kock",
    "PrabhSimran": "Prabhsimran Singh",
    "Nicholas Pooran": "Nicholas Pooran",
    "Anrich Norkje": "Anrich Nortje",
    "rinkusingh": "Rinku Singh",
    "Mahendra Singh Dhoni": "MS Dhoni",
    "Hardik Pandya": "Hardik Pandya",
    "Abishek Porel": "Abhishek Porel",
    "@josbuttler": "Jos Buttler",
    "heinrich klaasen": "Heinrich Klaasen",
    "Shahbaz": "Shahbaz Nadeem",
    "McGurk": "Undefined",
    "Jhulan Goswami": "Jhulan Goswami",
    "अक्षर": "Undefined",
    "Rahul": "Rahul Dravid",
    "ऋतुराज": "Ruturaj Gaikwad",
    "StLouisBlues": "Undefined",
    "Daryl Mitchell": "Daryl Mitchell",
    "rajasthanroyals": "Rajasthan Royals",
    "sachin_rt": "Sachin Tendulkar",
    "Hooda": "Deepak Hooda",
    "Lucknow super giants (LSG)": "Lucknow Super Giants",
    "vennela kishore": "Vennela Kishore",
    "sanju samson": "Sanju Samson",
    "Sunil Narine": "Sunil Narine",
    "Shreyas": "Shreyas Iyer",
    "#RuturajGaikwad": "Ruturaj Gaikwad",
    "Saiyami Kher": "Saiyami Kher",
    "kkr": "Kolkata Knight Riders",
    "Gautam Gambhir": "Gautam Gambhir",
    "fafduplessis": "Faf du Plessis",
    "பட்டிதர்": "Pat Cummins",
    "PunjabKings": "Punjab Kings",
    "Ms Dhoni": "MS Dhoni",
    "LeeSeungGi": "Lee Seung Gi",
    "Wasim Akram": "Wasim Akram",
    "Saratendulkar": "Sachin Tendulkar",
    "Harsha Bhogle": "Harsha Bhogle",
    "TlayAnl1903": "Undefined",
    "PrabhsimranSingh": "Prabhsimran Singh",
    "Kachiguda Klassen": "Heinrich Klaasen",
    "Keshav Maharaj": "Keshav Maharaj",
    "Chahal": "Yuzvendra Chahal",
    "Klaasen": "Heinrich Klaasen",
    "Prabhsimran Singh": "Prabhsimran Singh",
    "Yuzi Chahal": "Yuzvendra Chahal",
    "Mahipal Lomror": "Mahipal Lomror",
    "Pathirana": "Matheesha Pathirana",
    "HULK": "Undefined",
    "Irfan Pathan": "Irfan Pathan",
    "nithish Kumar Reddy": "Nithish Reddy",
    "Thakur": "Shardul Thakur",
    "Manish Pandey": "Manish Pandey",
    "पंत": "Rishabh Pant",
    "Andre Russell": "Andre Russell",
    "shahbazahmed": "Shahbaz Ahmed",
    "Shreevats Goswami": "Shreevats Goswami",
    "Adhem": "Undefined",
    "Garuka Sanketh": "Undefined",
    "#Natarajan": "T Natarajan",
    "head": "Undefined",
    "Devdutt Padikkal": "Devdutt Padikkal",
    "KKRUniverse": "Kolkata Knight Riders",
    "king khan": "Shahrukh Khan",
    "RajatPatidar": "Rajat Patidar",
    "Ashish Nehra": "Ashish Nehra",
    "Narayan": "Narayan Jagadeesan",
    "@LucknowIPL": "Lucknow Super Giants",
    "ShubmanGill": "Shubman Gill",
    "PHIL SALT": "Phil Salt",
    "Ananya Panday": "Ananya Panday",
    "PKBS": "Undefined",
    "Surya Kumar Yadav": "Suryakumar Yadav",
    "Shabaz": "Undefined",
    "RuturajGaikwad": "Ruturaj Gaikwad",
    "AbhishekSharma": "Abhishek Sharma",
    "rahultewatia": "Rahul Tewatia",
    "urstrulyMahesh": "Mahesh Babu",
    "Gilly": "Adam Gilchrist",
    "Angkrish Raghuvanshi": "Undefined",
    "Mohammad Kaif": "Mohammad Kaif",
    "bravo": "Dwayne Bravo",
    "Virat Singh": "Virat Singh",
    "Shreyas Iyer": "Shreyas Iyer",
    "viratkohli": "Virat Kohli",
    "SamCurran": "Sam Curran",
    "Shimron Hetmyer": "Shimron Hetmyer",
    "Sathish": "Sathish",
    "SUNIL NARINE": "Sunil Narine",
    "Mohit Sharma": "Mohit Sharma",
    "Shivam Dubey": "Shivam Dube",
    "V Kohli": "Virat Kohli",
    "Gaikwad": "Ruturaj Gaikwad",
    "RohanGava9": "Undefined",
    "Joy Bhattacharya": "Joy Bhattacharjya",
    "Sachintendulkar": "Sachin Tendulkar",
    "patcummins": "Pat Cummins",
    "RR players": "Rajasthan Royals",
    "Morne Morkel": "Morne Morkel",
    "Ricky Ponting": "Ricky Ponting",
    "Nitish": "Nitish Rana",
    "Thalaivar": "MS Dhoni",
    "Padikkal": "Devdutt Padikkal",
    "Tilak Varma": "Tilak Varma",
    "josbuttler": "Jos Buttler",
    "@iamsrk": "Shahrukh Khan",
    "पाटीदार": "Undefined",
    "Jake Fraser-McGurk": "Jake Fraser-McGurk",
    "travshead": "Travis Head",
    "HardikPandya": "Hardik Pandya",
    "Gaurav Kapoor": "Gaurav Kapoor",
    "virat kohli": "Virat Kohli",
    "Pant": "Rishabh Pant",
    "Phillips": "David Phillips",
    "Kavya Maran": "Kavya Maran",
    "Simon Doull": "Simon Doull",
    "Maxwell": "Glenn Maxwell",
    "Ankul": "Ankul Roy",
    "Sourav Ganguly": "Sourav Ganguly",
    "de kock": "Quinton de Kock",
    "pant": "Rishabh Pant",
    "SHAH RUKH KHAN": "Shahrukh Khan",
    "JosButtler": "Jos Buttler",
    "Punjab Kings": "Punjab Kings",
    "Samad": "Abdul Samad",
    "shikhardhawan": "Shikhar Dhawan",
    "Butler": "Jos Buttler",
    "SKY": "Suryakumar Yadav",
    "SuhanaKhan": "Suhana Khan",
    "Kolkata Knight Riders": "Kolkata Knight Riders",
    "Gujarat Titans": "Gujarat Titans",
    "Dube": "Shivam Dube",
    "MI": "Mumbai Indians",
    "KLRahul": "KL Rahul",
    "Heinrich Klaasen": "Heinrich Klaasen",
    "Parag": "Riyan Parag",
    "FafDuPlessis": "Faf du Plessis",
    "SDV": "Suryakumar Yadav",
    "MoeenAli": "Moeen Ali",
    "Kane Williamson": "Kane Williamson",
    "राजत पाटीदार": "Rajat Patidar",
    "Tha7a": "Undefined",
    "RR fans": "Rajasthan Royals",
    "Ice Man": "Undefined",
    "Sai": "Undefined",
    "Rajat Patidar": "Rajat Patidar",
    "Quinton de Kock": "Quinton de Kock",
    "Mustafizur": "Mustafizur Rahman",
    "Matheesha Pathirana": "Matheesha Pathirana",
    "@rajasthanroyals": "Rajasthan Royals",
    "Riyan Parag": "Riyan Parag",
    "Jasiwal": "Undefined",
    "Suyash Sharma": "Suyash Prabhudessai",
    "Pawankalyan": "Pawan Kalyan",
    "Sam Curran": "Sam Curran",
    "Lucknow Super Giants": "Lucknow Super Giants",
    "Sandeep bhai": "Sandeep Sharma",
    "Mohammad Shami": "Mohammed Shami",
    "Rohan Gavaskar": "Rohan Gavaskar",
    "Natrajan": "T Natarajan",
    "Cummins": "Pat Cummins",
    "Aaron Finch": "Aaron Finch",
    "shubmangill": "Shubman Gill",
    "Venkat Prabhu": "Venkat Prabhu",
    "Liam Livingstone": "Liam Livingstone",
    "Stoinis": "Marcus Stoinis",
    "Sakaria": "Chetan Sakariya",
    "PAT CUMMINS": "Pat Cummins",
    "Tilak verma": "Tilak Varma",
    "Matthew Wade": "Matthew Wade",
    "K. L. Rahul": "KL Rahul",
    "GG": "Gautam Gambhir",
    "PrabhsimranSingh": "Prabhsimran Singh",
    "Kachiguda Klassen": "Undefined",
    "Keshav Maharaj": "Keshav Maharaj",
    "Chahal": "Yuzvendra Chahal",
    "Klaasen": "Heinrich Klaasen",
    "Prabhsimran Singh": "Prabhsimran Singh",
    "Yuzi Chahal": "Yuzvendra Chahal",
    "Mahipal Lomror": "Mahipal Lomror",
    "Pathirana": "Matheesha Pathirana",
    "HULK": "Undefined",
    "Irfan Pathan": "Irfan Pathan",
    "nithish Kumar Reddy": "Nithish Reddy",
    "Thakur": "Shardul Thakur",
    "Manish Pandey": "Manish Pandey",
    "पंत": "Rishabh Pant",
    "Andre Russell": "Andre Russell",
    "shahbazahmed": "Shahbaz Ahmed",
    "Shreevats Goswami": "Shreevats Goswami",
    "Adhem": "Undefined",
    "Garuka Sanketh": "Undefined",
    "#Natarajan": "T Natarajan",
    "head": "Undefined",
    "Devdutt Padikkal": "Devdutt Padikkal",
    "KKRUniverse": "Kolkata Knight Riders",
    "king khan": "Shahrukh Khan",
    "RajatPatidar": "Rajat Patidar",
    "Ashish Nehra": "Ashish Nehra",
    "Narayan": "Narayan Jagadeesan",
    "@LucknowIPL": "Lucknow Super Giants",
    "Shashank": "Undefined",
    "shashanksing": "Undefined",
    "ShubmanGill": "Shubman Gill",
    "PHIL SALT": "Phil Salt",
    "Ananya Panday": "Ananya Panday",
    "PKBS": "Undefined",
    "Surya Kumar Yadav": "Suryakumar Yadav",
    "Shabaz": "Undefined",
    "Fraser McGurk": "Undefined",
    "Shabhaz Ahmed": "Shahbaz Ahmed",
    "RuturajGaikwad": "Ruturaj Gaikwad",
    "AbhishekSharma": "Abhishek Sharma",
    "rahultewatia": "Rahul Tewatia",
    "Marcus Stoinis": "Marcus Stoinis",
    "Jasprit Bumrah": "Jasprit Bumrah",
    "urstrulyMahesh": "Mahesh Babu",
    "Gilly": "Adam Gilchrist",
    "Angkrish Raghuvanshi": "Undefined",
    "Mohammad Kaif": "Mohammad Kaif",
    "bravo": "Dwayne Bravo",
    "Virat Singh": "Virat Singh",
    "Shreyas Iyer": "Shreyas Iyer",
    "viratkohli": "Virat Kohli",
    "Abhishek Sharma": "Abhishek Sharma",
    "SamCurran": "Sam Curran",
    "Shimron Hetmyer": "Shimron Hetmyer",
    "Sathish": "Sathish",
    "SUNIL NARINE": "Sunil Narine",
    "Mohit Sharma": "Mohit Sharma",
    "Shivam Dubey": "Shivam Dube",
    "V Kohli": "Virat Kohli",
    "Gaikwad": "Ruturaj Gaikwad",
    "RohanGava9": "Undefined",
    "Joy Bhattacharya": "Joy Bhattacharjya",
    "Sachintendulkar": "Sachin Tendulkar",
    "patcummins": "Pat Cummins",
    "RR players": "Rajasthan Royals",
    "Morne Morkel": "Morne Morkel",
    "Ruturaj Gaikwad": "Ruturaj Gaikwad",
    "Ricky Ponting": "Ricky Ponting",
    "Nitish": "Nitish Rana",
    "Thalaivar": "MS Dhoni",
    "Padikkal": "Devdutt Padikkal",
    "Tilak Varma": "Tilak Varma",
    "josbuttler": "Jos Buttler",
    "@iamsrk": "Shahrukh Khan",
    "पाटीदार": "Undefined",
    "Jake Fraser-McGurk": "Jake Fraser-McGurk",
    "travshead": "Travis Head",
    "HardikPandya": "Hardik Pandya",
    "Gaurav Kapoor": "Gaurav Kapoor",
    "virat kohli": "Virat Kohli",
    "Pant": "Rishabh Pant",
    "Phillips": "David Phillips",
    "Kavya Maran": "Kavya Maran",
    "Simon Doull": "Simon Doull",
    "Maxwell": "Glenn Maxwell",
    "Ankul": "Ankul Roy",
    "Sourav Ganguly": "Sourav Ganguly",
    "de kock": "Quinton de Kock",
    "pant": "Rishabh Pant",
    "SHAH RUKH KHAN": "Shahrukh Khan",
    "JosButtler": "Jos Buttler",
    "Punjab Kings": "Punjab Kings",
    "Samad": "Abdul Samad",
    "shikhardhawan": "Shikhar Dhawan",
    "Butler": "Jos Buttler",
    "SKY": "Suryakumar Yadav",
    "SuhanaKhan": "Suhana Khan",
    "Kolkata Knight Riders": "Kolkata Knight Riders",
    "Gujarat Titans": "Gujarat Titans",
    "Dube": "Shivam Dube",
    "MI": "Mumbai Indians",
    "KLRahul": "KL Rahul",
    "Heinrich Klaasen": "Heinrich Klaasen",
    "Parag": "Riyan Parag",
    "FafDuPlessis": "Faf du Plessis",
    "SDV": "Suryakumar Yadav",
    "MoeenAli": "Moeen Ali",
    "Kane Williamson": "Kane Williamson",
    "राजत पाटीदार": "Rajat Patidar",
    "Tha7a": "Undefined",
    "RR fans": "Rajasthan Royals",
    "Ice Man": "Undefined",
    "Sai": "Undefined",
    "Rajat Patidar": "Rajat Patidar",
    "Quinton de Kock": "Quinton de Kock",
    "Mustafizur": "Mustafizur Rahman",
    "Matheesha Pathirana": "Matheesha Pathirana",
    "@rajasthanroyals": "Rajasthan Royals",
    "Riyan Parag": "Riyan Parag",
    "Jasiwal": "Undefined",
    "Suyash Sharma": "Suyash Prabhudessai",
    "Pawankalyan": "Pawan Kalyan",
    "not mentioned": "Undefined",
    "Lucknow Super Giants": "Lucknow Super Giants",
    "Sandeep bhai": "Sandeep Sharma",
    "Mohammad Shami": "Mohammed Shami",
    "Rohan Gavaskar": "Rohan Gavaskar",
    "Natrajan": "T Natarajan",
    "Cummins": "Pat Cummins",
    "Aaron Finch": "Aaron Finch",
    "shubmangill": "Shubman Gill",
    "Venkat Prabhu": "Venkat Prabhu",
    "Liam Livingstone": "Liam Livingstone",
    "Stoinis": "Marcus Stoinis",
    "Sakaria": "Chetan Sakariya",
    "PAT CUMMINS": "Pat Cummins",
    "Tilak verma": "Tilak Varma",
    "Matthew Wade": "Matthew Wade",
    "K. L. Rahul": "KL Rahul",
    "GG": "Gautam Gambhir",
    "Shabhaz Ahmad": "Shahbaz Ahmed",
    "LSG": "Lucknow Super Giants",
    "Abhishekh Sharma": "Abhishek Sharma",
    "Jake Fraser": "Jake Fraser-McGurk",
    "Manoj Tiwary": "Manoj Tiwary",
    "Jonny Bairstow": "Jonny Bairstow",
    "MStoinis": "Marcus Stoinis",
    "Umpires": "Undefined",
    "deepak_chahar9": "Deepak Chahar",
    "ravindra jadeja": "Ravindra Jadeja",
    "Rasikh Salam": "Rasikh Salam",
    "Jos Buttler": "Jos Buttler",
    "Bumrah": "Jasprit Bumrah",
    "Omarzai": "Qais Ahmad",
    "NARINE": "Sunil Narine",
    "Jadeja": "Ravindra Jadeja"
}
